name: Java Selenium Tests

on:
  schedule:
    - cron: '30 3 * * *'  # 9 AM IST is 3:30 AM UTC
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven
          mvn -version  # Ensure Maven is installed and working

      - name: Install dependencies (including ChromeDriver)
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget
          wget https://chromedriver.storage.googleapis.com/113.0.5672.63/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          chromedriver --version  # Verify ChromeDriver installation

      - name: Build with Maven
        run: mvn clean install

      - name: Run Selenium Tests
        run: mvn test

      - name: Clean up
        run: rm -f chromedriver
