name: Java Selenium Tests

on:
  push:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Setup WebDriver Manager
      run: |
        echo "Setting up WebDriver Manager"
        # WebDriver Manager automatically downloads the correct version of ChromeDriver
        mvn io.github.bonigarcia:webdriver-manager:5.6.0:download

    - name: Set up Google Chrome
      run: |
        sudo apt-get update -y
        sudo apt-get install -y google-chrome-stable

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Test with Maven
      run: mvn test -Dsurefire.suiteXmlFiles=testng.xml

    - name: Upload Test Results
      uses: actions/upload-artifact@v4  # Updated to v4
      if: always()
      with:
        name: Test Results
        path: target/surefire-reports
